const ADD_INIT_POKEMONS = "ADD_INIT_POKEMONS";
const ADD_ACTIVE = "ADD_ACTIVE";
const FILTER_BY_TYPE = "FILTER_BY_TYPE";
const FILTER_BY_NAME = "FILTER_BY_NAME";
export default { ADD_INIT_POKEMONS, ADD_ACTIVE, FILTER_BY_TYPE, FILTER_BY_NAME }